#!/usr/bin/env ruby

step = 2

ARGV.each do |a|
	case a
	when "up"
		`amixer sset Master #{step}dB+`
	when "down"
		`amixer sset Master #{step}dB-`
	when "toggle"
		`amixer sset Master toggle`
	end
end
