#!/usr/bin/ruby
require 'optparse'

$n = if ARGV.delete('-v') then '' else "\n" end

if ARGV[0] and ARGV[0].downcase == 'birthday'
	if ARGV[1]
		year = Integer(ARGV[1])
		max = if year % 4 != 0 then 365 else 366 end
	else max = 365 end
	day = rand(max)

	def say(m, d)
		print ("/%02d/%02d" % [m, d]), $n
		exit
	end

	if day == 0 then say 0, 0 end

	def try(d, m, x)
		if d <= x then say m, d end
		return d - x
	end

	([30, 31, 30] * 4).each_with_index { |x, m| day = try day, m+1, x }
end
